import Foundation
import CZUtils

public class Promise {
  public typealias Input = Any
  public typealias Result = Any
  
  /// Resolve callback closure.
  public typealias Resolve = (Input?) -> Void
  /// Reject callback closure.
  public typealias Reject = (Error?) -> Void
  /// Pre-execution closure: the real preExecution will be when resolve() / reject() gets called.
  public typealias Execution = (@escaping Resolve, @escaping Reject) -> Void
  private let preExecution: Execution
  
  /// Error of preExecution.
  private var error: Error?
  
  /// Then callback closure.
  public typealias Then<T, U> = (T?) -> U?
  
  /// Array of chaining then closures.
  /// - Note: RootPromise maintains all `thenClosures`, instead of each Promise maintaining its own.
  private var thenClosures = [Then<Input, Promise>]()
  /// Promises generated by `thenClosure` asynchronously.
  // private var thenPromises = [Promise]()
  private var currPromiseIndex = 0

  /// Catch callback closure.
  public typealias Catch = (Error?) -> Void
  private var catchClosure: Catch?
  
  /// Semaphore for async/await signal.
  private var semaphore: DispatchSemaphore?
  
  private var externalInput: Input?
  private weak var rootPromise: Promise?
  private var nextPromise: Promise?
  
  public static var allPromisesSuccessString: String {
    return "Succeed to execute all promises."
  }
  
  /// Initialize with `preExecution` closure.
  /// Call `resolve()` on success, and call `reject()` on failure.
  public init(root rootPromise: Promise?,
              _ preExecution: @escaping Execution) {
    self.rootPromise = rootPromise
    self.preExecution = preExecution
    
    if self.rootPromise == nil {
      // Set `rootPromise` with self if it's nil, which will be held weak reference.
      self.rootPromise = self
    }
  }
  
  /// `thenClosure` that will be called by `resolve()`: `then()` returns Promise.
  @discardableResult
  public func then(_ thenClosure: @escaping Then<Input, Promise>) -> Promise {
    // 1. Store `thenClosure`.
    let hasQueuedThenClosure = rootPromise!.hasQueuedThenClosure()
    rootPromise?.enqueueThenClosure(thenClosure)
    
    // 2. preExecution(): if has no thenClosure in queue - no previous resolve() left.
    // The remaining promises will be prepared in its prev promise's resolve().
    // `preExecution`: just prepare - the real execution will be when resolve() / reject() gets called.
    // if currPromiseIndex == 0
    if !hasQueuedThenClosure {
      preExecution(resolve, reject)
    }
    
    return self
  }
  
  /// `then` function that will be called on `resolve()`.
//  //public func then<Output>(_ thenClosure: @escaping Then<Input, Output>) -> Promise<Output> {
//  public func then<Output>(_ thenClosure: @escaping Then<Input, Output>) -> Promise<Output> {
//    // 1. Store `then`.
//    self.thenClosure = { (input) in
//      return thenClosure(input as! Input)
//    }
//
//    // * New Promise: its `.then()` will be set externally.
//    let nextPromise = Promise<Output> { (resolve, reject) in }
//    self.nextPromise = nextPromise as! Promise<Any>
//
//    // 2. Trigger preExecution.
//    if self.externalInput != nil {
//      // Resolve automatically with previousResult: for non-first promise.
//      resolve(self.externalInput)
//    } else {
//      // Start pre-preExecution `preExecution`: the real preExecution will be when resolve() / reject() gets called.
//      preExecution(resolve, reject)
//    }
//
//    // 3. Return new Promise.
//    return nextPromise
//    // return self
//  }
//
  /// `catch` function that will be called on `reject()`.
  @discardableResult
  public func `catch`(_ catchClosure: @escaping Catch) -> Promise {
    self.catchClosure = catchClosure
    return self
  }
  
  // MARK: - RootPromise
  
  func hasQueuedThenClosure() -> Bool {
    return thenClosures.count > 0
  }
  
  func enqueueThenClosure(_ thenClosure: @escaping Then<Input, Promise>) {
    thenClosures.append(thenClosure)
  }
  
  func dequeNextThenClosures() -> Then<Input, Promise>? {
    guard hasQueuedThenClosure() else {
      return nil
    }
    let nextThenClosure = thenClosures.removeFirst()
    currPromiseIndex += 1
    return nextThenClosure
    
//    guard currPromiseIndex <= thenClosures.count - 1 else {
//      return nil
//    }
//    let nextThenClosure = thenClosures[currPromiseIndex]
//    currPromiseIndex += 1
//    return nextThenClosure
  }
  
}


// MARK: - Resolve / Reject

private extension Promise {
  /// Function will be called on preExecution success.
  func resolve(_ input: Input?) {
    guard let nextThenClosure = rootPromise?.dequeNextThenClosures() else {
      // If completes the last promise, then return.
      dbgPrintWithFunc(self, "Completed all promises! currPromiseIndex = \(currPromiseIndex), thenClosures.count = \(thenClosures.count)")
      return
    }
    let nextInput = input
    
    // Set `nextInput` to `nextPromise`: generate `nextPromise` with `thenClosures` at `currPromiseIndex`.
    nextPromise = nextThenClosure(nextInput)
    
    // Call nextPromise's preExecution: prepare.
    nextPromise?.preExecution(nextPromise!.resolve, nextPromise!.reject)
    
    // No need to call nextPromise: will be called by nextPromise itself.
    // nextPromise?.resolve(nextInput)    
  }
  
  /// Function will be called on preExecution failure.
  func reject(_ error: Error?) {
    // Call `then` with `error`.
    catchClosure?(error)
  }
}
